# Jupyter Book Configuration
# Learn more at https://jupyterbook.org/customize/config.html

title: Deep Learning Tutorials for Nuclear Physics at APS-DNP 2025
author: Karthik Suresh & Cristiano Fanelli
copyright: "2025"
logo: ""
only_build_toc_files: true
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off  # Don't execute notebooks during build

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: dnp2025-tutorials.tex

# In _config.yml
bibtex_bibfiles:
    - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ai4eic/DNP2025-tutorials
  path_to_book: .  # Path to the book (root in this case)
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_navbar: true
  baseurl: https://ai4eic.github.io/DNP2025-tutorials/

# Sphinx configuration
sphinx:
  extra_extensions:
    - sphinx.ext.mathjax
    - sphinxcontrib.mermaid
  config:
    html_theme_options:
      repository_url: https://github.com/ai4eic/DNP2025-tutorials
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Parse and render MyST markdown
parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - colon_fence
    - deflist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution