# Jupyter Book Configuration
# Learn more at https://jupyterbook.org/customize/config.html

title: Deep Learning Tutorials for Nuclear Physics at APS-DNP 2025
author: Karthik Suresh & Cristiano Fanelli
copyright: "2025"
logo : images/AI4eic_logo4.png  # A path to the book logo
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off  # Don't execute notebooks during build

# In _config.yml
bibtex_bibfiles:
    - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ai4eic/DNP2025-tutorials
  path_to_book: .  # Path to the book (root in this case)
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_navbar: true
  baseurl: https://ai4eic.github.io/DNP2025-tutorials/
  extra_footer : "DNP 2025 Data Science Workshop"  # Will be displayed underneath the footer.
  analytics:
      plausible_analytics_url: https://plausible.io/js/script.js

  comments:
    hypothesis              : true
    utterances              : 
                            repo: "ai4eic/DNP2025-tutorials"

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : "jupyterlab"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "https://colab.research.google.com" # The URL of Google Colab (https://colab.research.google.com)

# Sphinx configuration
sphinx:
  extra_extensions:
    - sphinx.ext.mathjax
    - sphinxcontrib.mermaid
    - sphinx_design
  config:
    html_theme_options:
      repository_url: https://github.com/ai4eic/DNP2025-tutorials
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Parse and render MyST markdown
parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - colon_fence
    - deflist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution